### ISSUE TITLE
LibrePro activate issue

### ISSUE THREAD

**Issue by zhhehj13** [gui-dos/DiaBLE#11]
when I activate the LibrePro, I find the "readerSerial" in Class "LibrePro" is Empty. 
launch the app, do nothing except activation
you will find this error

**Comment by gui-dos** [comment]
Those Libre Pro code and firmware dumps were passed to me by @MarekM60. If you decompile his [iDroplet Pro](https://droplet.rocks/) Android app you can find out that those methods correspond.

Marek was taking part in the Discussions of my previous repo and even helped Blepixel's BLEScanner product manager to activate Pro sensors by using his reader serials (there is a CRC32 check involved).

I never tested real Libre Pros and I got no feedback from the Bubble and Droplet current sellers: unfortunately it seems that Marek's private repos probably have been lost forever since there has have been no further updates. :-(

**Comment by gui-dos** [comment]
The latest LiNkBluCon lets you scan a sensor directly via NFC. I am noticing that in the Pro activation command they are replacing the latest digit of a reader serial number with a kind of timestamp. That epoch fixed at 31/12/2012 is a stranger creature I never met...
<img width="1312" alt="LinkBluCon-Pro-Activation" src="https://user-images.githubusercontent.com/7220550/212640221-dfa59eb7-287e-4fa6-a8e2-31c3a51ee3a6.png">
