### ISSUE TITLE
Calibration

### ISSUE THREAD

**Issue by advatar** [gui-dos/DiaBLE#17]
Cool project! Just built and tested with my Libre 1. It works like a charm but the value I get is 1 mol/L less than what I get with the official app. Have you seen that before or should I just calibrate accordingly?

**Comment by gui-dos** [comment]
The temperature-based calibration algorithm has been reversed from LibreLink 2.3 (I shared it with Glucose Direct and xDrip4iOS5) and the result can differ noticeably from the latest LL releases. I am not smoothing the curves and I don’t project the trend values into the future to compensate the interstitial delay (like LibreTransmitter [attempts](https://github.com/dabear/LibreTransmitter/commit/49b50d7995955b76861440e5e34a0accd064d18f)) since the exact algorithms behind such further stages have not been reversed, AFAIK.
