### ISSUE TITLE
Documentation on NFC & BLE for Libre 2

### ISSUE THREAD

**Issue by ikarus23** [gui-dos/DiaBLE#3]
Hi, I'm an NFC and BLE enthusiast having access to some discarded Libre2 sensors. I've just stumbled across this app and was wondering how the whole NFC (and BLE) stuff works. However, I don't have any clue about Xcode.

Is there some documentation available online? Like "what is the command sequence to read the config via NFC?". I've saw there is something like this in the code.
|A3|1b6a|00a1|0f|
|-|-|-|-|
|rawRead?|Backdoor for Libre2|Address to config|Bytes to read?|

But I had no success so far. There seem to be other interesting functions on how to activate BLE via NFC?!

Also, I don't have an iPhone...
Can you point me in some direction?

**Comment by gui-dos** [comment]
Sorry for the confusion I introduced with f793311.

The 0xA3 command works only with the Libre 1.

In the Libre 2 the first byte in the parameters you pass to the “universal” 0xA1 command is a “subcommand” code: 0x1a for activating a sensor, 0x1e for enabling the BLE streaming of data.

I tried to abstract the constant 0x16ba as a “backdoor” because it is not generated dynamically for the commands 0x1a, 0x1c and 0x1d. I am simply using it again as a UInt16 with 2e9b6ca.

**Comment by gui-dos** [comment]
Added a Quick Help for nfcCommand(_ code: Subcommand) with 9edb0bb

**Comment by ikarus23** [comment]
Hi! Thanks for the feedback and pointers. Is there a list with all available commands somewhere? Or is it just reading your code?

**Comment by gui-dos** [comment]
I am not reverse engineering the Libre 2 by myself. It is an ongoing effort. The vendor already took down other repos and apps from the stores: I am publishing only what is working for my personal needs ;-)

**Comment by ikarus23** [comment]
Yeah, I understand. Thanks anyways! I will check the code then ;)
